-- musing/init.lua — neovim plugin entry point

local M = {}

M.config = {
  -- File patterns to auto-analyze (empty = manual only)
  filetypes = { "text", "markdown", "" },
  -- Inference endpoint (nil = heuristics only)
  llm_endpoint = nil,
  -- Confidence threshold: below this, flag for LLM/user review
  confidence_threshold = 0.7,
  -- Show gutter signs
  signs = true,
  -- Show virtual text
  virtual_text = true,
}

local heuristics = require("musing.heuristics")
local sidecar = require("musing.sidecar")
local infer = require("musing.infer")

local ns = vim.api.nvim_create_namespace("musing")

-- Sign definitions
local sign_map = {
  heading = { text = "H", hl = "Title" },
  paragraph = { text = "¶", hl = "Comment" },
  list = { text = "•", hl = "Identifier" },
  code = { text = "█", hl = "String" },
  blockquote = { text = "▌", hl = "Special" },
  table = { text = "╦", hl = "Type" },
  thematic_break = { text = "─", hl = "NonText" },
  blank = nil, -- no sign for blanks
}

--- Clear all musing decorations from a buffer.
local function clear(buf)
  vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
end

--- Apply gutter signs and virtual text for classified elements.
local function display(buf, elements, overrides)
  clear(buf)
  for _, el in ipairs(elements) do
    local key = el.start_line == el.end_line
      and tostring(el.start_line)
      or (el.start_line .. "-" .. el.end_line)

    -- Apply override if present
    local etype = el.type
    if overrides[key] and overrides[key].type then
      etype = overrides[key].type
    end

    local sign = sign_map[etype]
    if not sign then goto continue end

    local line = el.start_line - 1 -- 0-indexed

    -- Sign
    if M.config.signs then
      vim.api.nvim_buf_set_extmark(buf, ns, line, 0, {
        sign_text = sign.text,
        sign_hl_group = sign.hl,
      })
    end

    -- Virtual text for low-confidence items
    if M.config.virtual_text and el.confidence and el.confidence < M.config.confidence_threshold then
      vim.api.nvim_buf_set_extmark(buf, ns, line, 0, {
        virt_text = { { " ?" .. etype, "DiagnosticWarn" } },
        virt_text_pos = "eol",
      })
    end

    ::continue::
  end
end

--- Apply LLM results back into the elements list.
local function apply_llm_results(elements, results)
  if not results then return end
  -- Build a lookup from line range to element index
  local by_key = {}
  for idx, el in ipairs(elements) do
    local key = el.start_line == el.end_line
      and tostring(el.start_line)
      or (el.start_line .. "-" .. el.end_line)
    by_key[key] = idx
  end
  for _, r in ipairs(results) do
    local idx = by_key[r.line]
    if idx and r.type then
      elements[idx].type = r.type
      elements[idx].confidence = 1.0
      if r.level then elements[idx].attrs.level = r.level end
      if r.style then elements[idx].attrs.style = r.style end
    end
  end
end

--- Analyze the current buffer.
function M.analyze(buf)
  buf = buf or vim.api.nvim_get_current_buf()
  local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  local filepath = vim.api.nvim_buf_get_name(buf)
  if filepath == "" then return end

  local elements = heuristics.classify(lines)

  -- Collect low-confidence elements for LLM
  local ambiguous = {}
  for _, el in ipairs(elements) do
    if el.confidence and el.confidence < (M.config.confidence_threshold + 0.1) then
      ambiguous[#ambiguous + 1] = el
    end
  end

  -- If LLM endpoint configured and there are ambiguous elements, call async
  if M.config.llm_endpoint and #ambiguous > 0 then
    -- Write heuristics-only sidecar first (instant feedback)
    sidecar.write(filepath, elements)
    local data = sidecar.read(filepath)
    display(buf, elements, data.overrides)

    -- Then refine async
    infer.call_async(M.config.llm_endpoint, lines, ambiguous, function(results)
      if results then
        apply_llm_results(elements, results)
        sidecar.write(filepath, elements)
        data = sidecar.read(filepath)
        display(buf, elements, data.overrides)
      end
    end)
  else
    sidecar.write(filepath, elements)
    local data = sidecar.read(filepath)
    display(buf, elements, data.overrides)
  end
end

--- Override an element type at the current cursor line.
function M.override(new_type)
  local buf = vim.api.nvim_get_current_buf()
  local filepath = vim.api.nvim_buf_get_name(buf)
  if filepath == "" then return end

  local cursor_line = vim.api.nvim_win_get_cursor(0)[1]
  local data = sidecar.read(filepath)

  -- Find which element range contains this line
  for key, _ in pairs(data.elements) do
    local s, e = key:match("^(%d+)%-(%d+)$")
    if not s then s = key:match("^(%d+)$"); e = s end
    s, e = tonumber(s), tonumber(e)
    if s and cursor_line >= s and cursor_line <= e then
      data.overrides[key] = { type = new_type }
      -- Rewrite sidecar preserving everything
      local f = io.open(sidecar.sidecar_path(filepath), "w")
      f:write("# Auto-generated by musing. Manual edits to [overrides] and [meta] are preserved.\n")
      f:write(sidecar.serialize(data))
      f:close()
      -- Re-display
      local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
      display(buf, heuristics.classify(lines), data.overrides)
      vim.notify("musing: overrode " .. key .. " → " .. new_type, vim.log.levels.INFO)
      return
    end
  end
end

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})

  -- Auto-analyze on save
  vim.api.nvim_create_autocmd("BufWritePost", {
    group = vim.api.nvim_create_augroup("musing", { clear = true }),
    callback = function(ev)
      local ft = vim.bo[ev.buf].filetype
      for _, pat in ipairs(M.config.filetypes) do
        if ft == pat then
          M.analyze(ev.buf)
          return
        end
      end
    end,
  })

  -- Commands
  vim.api.nvim_create_user_command("MusingAnalyze", function() M.analyze() end, {})
  vim.api.nvim_create_user_command("MusingOverride", function(cmd)
    M.override(cmd.args)
  end, { nargs = 1, complete = function()
    return { "heading", "paragraph", "list", "code", "blockquote", "table", "thematic_break", "blank" }
  end })
  vim.api.nvim_create_user_command("MusingClear", function()
    clear(vim.api.nvim_get_current_buf())
  end, {})
end

return M
